**PYTORCH**

It’s a Python based scientific computing package targeted at two sets of audiences:

A replacement for NumPy to use the power of GPUs
Deep learning research platform that provides maximum flexibility and speed
Features:

Interactively debugging PyTorch. Many users who have used both frameworks would argue that makes pytorch significantly easier to debug and visualize.

Clean support for dynamic graphs

Organizational backing from Facebook

Blend of high level and low level APIs

Highly used by researchers

Highly used for generative AI projects


In [ ]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import torch


In [ ]:

array=[[1,2,4],[4,5,67]]
first_array=np.array(array)
print(first_array)
print(type(first_array))

[[ 1  2  4]
 [ 4  5 67]]
<class 'numpy.ndarray'>


In [ ]:
import torch
tensor=torch.Tensor(array)
print(tensor)
print(type(tensor))
print(tensor.shape)



tensor([[ 1.,  2.,  4.],
        [ 4.,  5., 67.]])
<class 'torch.Tensor'>
torch.Size([2, 3])


Allocation is one of the most used technique in coding. Therefore lets learn how to make it with pytorch.

In order to learn, compare numpy and tensor

np.ones() = torch.ones()

np.random.rand() = torch.rand()


In [ ]:
print("Numpy {} \n".format(np.ones((2,3))))

Numpy [[1. 1. 1.]
 [1. 1. 1.]] 



In [ ]:
print(torch.ones(2,3))

tensor([[1., 1., 1.],
        [1., 1., 1.]])


In [ ]:
print(np.random.rand(2,3))

[[0.94334021 0.97632736 0.39757608]
 [0.41249037 0.13364528 0.46393572]]


In [ ]:
print(torch.rand(2,3))

tensor([[0.9430, 0.0698, 0.0918],
        [0.2644, 0.8451, 0.6791]])


Lets look at conversion between tensor and numpy arrays.

torch.from_numpy(): from numpy to tensor

numpy(): from tensor to numpy

In [ ]:
array=np.random.rand(2,2)
array

array([[0.89001243, 0.77017838],
       [0.75075511, 0.56305345]])

Numpy to tensor

In [ ]:
from_numpy_to_tensor=torch.from_numpy(array)
print(from_numpy_to_tensor)
print(type(from_numpy_to_tensor))

tensor([[0.8900, 0.7702],
        [0.7508, 0.5631]], dtype=torch.float64)
<class 'torch.Tensor'>


tensor to numpy

In [ ]:
from_tensor_to_numpy=from_numpy_to_tensor.numpy()
print(from_tensor_to_numpy)
print(type(from_tensor_to_numpy))

[[0.89001243 0.77017838]
 [0.75075511 0.56305345]]
<class 'numpy.ndarray'>


**Basic Math with Pytorch**

Resize: view()

a and b are tensor.

Addition: torch.add(a,b) = a + b

Subtraction: a.sub(b) = a - b

Element wise multiplication: torch.mul(a,b) = a * b

Element wise division: torch.div(a,b) = a / b

Mean: a.mean()

Standart Deviation (std): a.std()

In [ ]:
tensor=torch.ones(3,3)
tensor

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])

In [ ]:
tensor

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])

In [ ]:
print(tensor.view(9))
print(tensor.view(9).shape)

tensor([1., 1., 1., 1., 1., 1., 1., 1., 1.])
torch.Size([9])


In [ ]:
tensor2=torch.add(tensor,tensor)
print(tensor2)

tensor([[2., 2., 2.],
        [2., 2., 2.],
        [2., 2., 2.]])


In [ ]:
tensor

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])

In [ ]:
print(torch.sub(tensor,tensor))

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])


In [ ]:
print(torch.mul(tensor,tensor2))

tensor([[2., 2., 2.],
        [2., 2., 2.],
        [2., 2., 2.]])


In [ ]:
print(torch.div(tensor2,tensor))

tensor([[2., 2., 2.],
        [2., 2., 2.],
        [2., 2., 2.]])


In [ ]:
tensor3=torch.Tensor([1,3,4,6,7])
print("Mean {}".format(tensor3.mean()))
print(tensor3.mean())

Mean 4.199999809265137
tensor(4.2000)


In [ ]:
print("Std {}".format(tensor3.std()))

Std 2.387467384338379
